### PR TITLE
Updated index.html

### PR DESCRIPTION
**Pull request by YangQi007**
Added the custom color for the mapped reads chart

### CODE REVIEW

**Review by anderspitman — CHANGES_REQUESTED** [review]
@YangQi007 this branch doesn't work for me. Will you test it?

**Comment by YangQi007** [comment]
> @YangQi007 this branch doesn't work for me. Will you test it?

I think this branch is not linked to the right `iobio-charts` branch. Here is the link: d786e32336f09474794ecef14a509f3031f65c2b

**Comment by anderspitman** [comment]
The error I'm seeing is because chart is not defined:

`const chart = document.querySelector('#mapped-reads-chart');`

**Comment by anderspitman** [comment]
You might also need to update the iobio-charts version. You should be able to test this locally. Once it's working commit the working version

**Comment by YangQi007** [comment]
> The error I'm seeing is because chart is not defined:
> 
> `const chart = document.querySelector('#mapped-reads-chart');`

Fixed it.

**Comment by YangQi007** [comment]
> You might also need to update the iobio-charts version. You should be able to test this locally. Once it's working commit the working version

Is `bam.iobio` linked to the main branch of `iobio-charts`? How can I change the link to my working branch? Do you need to merger first?

**Comment by anderspitman** [comment]
git submodules link to a specific commit. You can see that displayed on GitHub here: https://github.com/iobio/bam.iobio/tree/main/lib.

And yeah I'll probably need to merge the iobio-charts PR before you can update this one

**Comment by anderspitman** [comment]
Ok the iobio-charts PR is merged. You should be able to pull the latest iobio-charts main branch and update this PR to be based off that commit.

**Review by anderspitman — APPROVED** [review]

**Pull request merged**
