### PR TITLE
Updated the axis format for histogram

### PR DESCRIPTION
**Pull request by YangQi007**

### CODE REVIEW

**Comment by anderspitman** [comment]
@YangQi007 should be able to merge this once you update it to the latest iobio-charts which I just merged

**Comment by anderspitman** [comment]
@YangQi007 sorry you'll need to pull one more time. I forgot to have you update iobio-charts to the latest iobio.viz before I merged.

**Comment by anderspitman** [comment]
@YangQi007 I'm not sure what the status is with this PR. I don't think anything needs to be done with iobio.viz. You should just need to merge the latest iobio-charts (1fcded8be1b92c89f5a40b174e3cbc556e5babf9) and then this will be good to go.

**Comment by YangQi007** [comment]
> @YangQi007 I'm not sure what the status is with this PR. I don't think anything needs to be done with iobio.viz. You should just need to merge the latest iobio-charts (1fcded8be1b92c89f5a40b174e3cbc556e5babf9) and then this will be good to go.

@anderspitman Ok, I reverted the prior commit and merged the latest iobio-charts. Please check it out again!

**Pull request merged**
