### PR TITLE
Reset the internal data state after the alignment file changes

### PR DESCRIPTION
**Pull request by YangQi007**

### CODE REVIEW

**Comment by anderspitman** [comment]
@YangQi007 what's the status of this one?

**Comment by YangQi007** [comment]
> @YangQi007 what's the status of this one?

This one was already resolved in the `iobio-charts`. I'll merge it here once you have updated the iobio-charts repo.

**Comment by YangQi007** [comment]
> I updated iobio-charts about 30 minutes ago. I think it's up to date

Just merged main to this branch.

**Comment by anderspitman** [comment]
But what does this PR actually do? It looks like it's only changes to iobio-charts, which should already be up to date in bam.iobio main.

**Comment by anderspitman** [comment]
I just updated iobio-charts again after merging #23

**Comment by YangQi007** [comment]
> But what does this PR actually do? It looks like it's only changes to iobio-charts, which should already be up to date in bam.iobio main.

Yes, this branch is related to #130 in `iobio-charts`. Now every time I update the code(sometimes changes happen in iobio-charts, sometimes not) in the bam.iobio, To be consistent, I open a new branch to track the update of `iobio-charts`.

**Comment by anderspitman** [comment]
Ah that makes sense. Seems like a good way to do it. I probably messed it up by merging iobio-charts manually.

I think if you merge the latest main into your branch, this PR shouldn't need to be merged anymore. I'll keep an eye out for these PRs in the future and avoid doing manual merges.

**Comment by anderspitman** [comment]
Also no need to take care of this until tomorrow.

**Comment by anderspitman** [comment]
@YangQi007 iobio-charts 130 is merged. What's the status of this one?

**Comment by YangQi007** [comment]
> @YangQi007 iobio-charts 130 is merged. What's the status of this one?

Just merged the main branch.  The conflicting was resolved now.

**Comment by anderspitman** [comment]
It looks like all this PR does is update iobio-charts to f54c65791778eba4e36050aefec91cedf266b68c, but that's an old version and the latest iobio-charts is 1fcded8be1b92c89f5a40b174e3cbc556e5babf9, so what would the effect of merging this be?

**Comment by YangQi007** [comment]
> It looks like all this PR does is update iobio-charts to f54c65791778eba4e36050aefec91cedf266b68c, but that's an old version and the latest iobio-charts is 1fcded8be1b92c89f5a40b174e3cbc556e5babf9, so what would the effect of merging this be?

If that's the case, yes, it will effect the bam.iobio after merging. There are two ways to resolve this:
1, I go to the branch https://github.com/iobio/iobio-charts/tree/yang_bam2.0_reset_internal_state_for_bamview to merge the latest main branch, then update the bam.iobio. 
2, We can just ignore this branch in bam.iobio, since the updates only happened in `iobio-charts`.

**Comment by anderspitman** [comment]
All your changes to iobio-charts are already incorporated into bam.iobio/main, so I think we can just close this.

**Pull request closed without merging**
